name: 'Matrix Review'

on:
  push:
  workflow_call:

env:
  STAGE: "int"
  CLUSTER_SHORT: "shr"
  CLUSTER_LONG: "aks-shared-int-sdc"
  PROJECT: "coreservices"
  RUNNER_TAG: "nonprod"

jobs:
  example_matrix:
    # runs-on: ubuntu-latest
    name: Bl ${{ matrix.tg_dir }}
    uses: ./.github/workflows/_reuse.yml
    strategy:
      max-parallel: 3
      matrix:
        tg_dir: [ "centralidp", "sharedidp", "bdrs", "ssi-credential-issuer", "discovery-finder", "bpn-discovery", "wallet-integration-layer", "policy-hub", "semantic-hub", "sync-semantic-models", "authority-schema-registry", "wallet-stub" ]
    with:
      tg_dir: ${{ matrix.tg_dir }}
    # steps:
    #   - run: |
    #       echo "Hello World {{ matrix.tg_dir }}"
    #       sleep 5
    